using System.Globalization;
using System.Text;
using core_api;
using Microsoft.Extensions.Options;

namespace core_api.Services;

public sealed class NginxTunnelConfigWriter(
    IOptions<TunnelingOptions> tunnelingOptions,
    IHostEnvironment hostEnvironment,
    ILogger<NginxTunnelConfigWriter> log) : INginxTunnelConfigWriter
{
    private readonly TunnelingOptions _options = tunnelingOptions.Value;

    public async Task WriteTunnelServerBlockAsync(string subdomain, int localPort, string? baseDomain, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(_options.NginxTunnelConfDirectory))
        {
            log.LogDebug("Tunneling:NginxTunnelConfDirectory is empty; skipping nginx snippet.");
            return;
        }

        var outputDir = Path.IsPathRooted(_options.NginxTunnelConfDirectory)
            ? _options.NginxTunnelConfDirectory
            : Path.GetFullPath(Path.Combine(hostEnvironment.ContentRootPath, _options.NginxTunnelConfDirectory));

        Directory.CreateDirectory(outputDir);

        var template = string.IsNullOrWhiteSpace(_options.NginxProxyPassTemplate)
            ? "http://host.docker.internal:{LocalPort}"
            : _options.NginxProxyPassTemplate;

        var upstreamBase = template
            .Replace("{LocalPort}", localPort.ToString(CultureInfo.InvariantCulture), StringComparison.Ordinal)
            .Replace("{Subdomain}", subdomain, StringComparison.Ordinal);

        var proxyPass = upstreamBase.TrimEnd('/') + "/";

        var serverNames = string.IsNullOrWhiteSpace(baseDomain)
            ? subdomain
            : $"{subdomain} {subdomain}.{baseDomain.Trim()}";

        var sb = new StringBuilder(1024);
        sb.AppendLine("# Generated by core-api POST api/tunnels/register — do not edit by hand.");
        sb.AppendLine("server {");
        sb.AppendLine("    listen 80;");
        sb.AppendLine($"    server_name {serverNames};");
        sb.AppendLine();
        sb.AppendLine("    location / {");
        sb.AppendLine($"        proxy_pass {proxyPass};");
        sb.AppendLine("        proxy_http_version 1.1;");
        sb.AppendLine("        proxy_set_header Upgrade $http_upgrade;");
        sb.AppendLine("        proxy_set_header Connection $connection_upgrade;");
        sb.AppendLine("        proxy_set_header Host $host;");
        sb.AppendLine("        proxy_set_header X-Real-IP $remote_addr;");
        sb.AppendLine("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
        sb.AppendLine("        proxy_set_header X-Forwarded-Proto $scheme;");
        sb.AppendLine("        proxy_read_timeout 3600s;");
        sb.AppendLine("        proxy_send_timeout 3600s;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var fileName = $"tunnel-{subdomain}.conf";
        var path = Path.Combine(outputDir, fileName);
        await File.WriteAllTextAsync(path, sb.ToString(), Encoding.UTF8, cancellationToken).ConfigureAwait(false);

        log.LogInformation("Wrote nginx tunnel config {Path} server_name={ServerNames} proxy_pass={ProxyPass}", path, serverNames, proxyPass);
    }
}
